version: v1

labels:
  - label: enhancement
    matcher:
      branch: "^feat/.*"

  - label: bug
    matcher:
      branch: "^fix/.*"

  - label: chore
    matcher:
      branch: "^chore/.*"

  - label: ci
    matcher:
      branch: "^ci/.*"

  - label: documentation
    matcher:
      branch: "^docs/.*"

  - label: refactor
    matcher:
      branch: "^refactor/.*"

  - label: revert
    matcher:
      branch: "^(revert/|revert-).*"

  - label: style
    matcher:
      branch: "^style/.*"

  - label: test
    matcher:
      branch: "^test/.*"
