name: Close stale

on:
  workflow_call:

jobs:
  stale:
    name: Close stale issues and pull requests
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Stale
        uses: actions/stale@v8
        with:
          days-before-issue-stale: 3
          days-before-issue-close: 2
          only-labels: question
          stale-issue-label: stale
          close-issue-message: This issue has been automatically closed due to inactivity. Feel free to comment in order to reopen.
