name: Label pull request

on:
  workflow_call:
  pull_request_target:
    types:
      - opened

jobs:
  label:
    name: Label
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Label pull request 🏷️
        uses: fuxingloh/multi-labeler@v2.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-repo: zeshuaro/github-actions-workflows
