name: Pull request actions

on:
  workflow_call:
  pull_request:

jobs:
  check-typos:
    name: Check typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6

      - name: Check spellings 📝
        uses: crate-ci/typos@v1.45.0
